"""
Coin analysis entity - Stores Gemini analysis results.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional


@dataclass
class GeminiInsight:
    """Structured insight generated by Gemini analyst."""
    
    trend: str  # bullish, bearish, sideways
    momentum: str  # strong, moderate, weak
    volatility_score: float  # 0.0 to 1.0
    volume_trend: str  # increasing, decreasing, stable
    key_observations: list[str] = field(default_factory=list)
    support_levels: list[str] = field(default_factory=list)
    resistance_levels: list[str] = field(default_factory=list)
    risk_factors: list[str] = field(default_factory=list)
    opportunity_factors: list[str] = field(default_factory=list)
    data_quality_notes: str = ""
    raw_analysis: str = ""  # Full text analysis
    
    def to_dict(self) -> dict:
        """Convert to dictionary for storage."""
        return {
            "trend": self.trend,
            "momentum": self.momentum,
            "volatility_score": self.volatility_score,
            "volume_trend": self.volume_trend,
            "key_observations": self.key_observations,
            "support_levels": self.support_levels,
            "resistance_levels": self.resistance_levels,
            "risk_factors": self.risk_factors,
            "opportunity_factors": self.opportunity_factors,
            "data_quality_notes": self.data_quality_notes,
            "raw_analysis": self.raw_analysis,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "GeminiInsight":
        """Create from dictionary."""
        return cls(
            trend=data.get("trend", "unknown"),
            momentum=data.get("momentum", "unknown"),
            volatility_score=float(data.get("volatility_score", 0.0)),
            volume_trend=data.get("volume_trend", "unknown"),
            key_observations=data.get("key_observations", []),
            support_levels=data.get("support_levels", []),
            resistance_levels=data.get("resistance_levels", []),
            risk_factors=data.get("risk_factors", []),
            opportunity_factors=data.get("opportunity_factors", []),
            data_quality_notes=data.get("data_quality_notes", ""),
            raw_analysis=data.get("raw_analysis", ""),
        )


@dataclass
class CoinAnalysis:
    """Complete analysis record for a coin stored in DynamoDB."""
    
    # Primary key: {TICKER}-{COINNAME}
    partition_key: str
    ticker: str
    coin_name: str
    symbol: str  # Trading pair symbol (e.g., BTCUSDT)
    
    # Market data snapshot
    current_price: str
    price_change_24h: str
    volume_24h: str
    volume_rank: int
    
    # Price history (recent candles)
    price_history: list[dict] = field(default_factory=list)
    
    # Gemini analysis
    gemini_insight: Optional[GeminiInsight] = None
    
    # Metadata
    analysis_timestamp: datetime = field(default_factory=datetime.now)
    data_source: str = "bitget"
    version: str = "1.0"
    
    def to_dynamodb_item(self) -> dict[str, Any]:
        """Convert to DynamoDB item format."""
        item = {
            "pk": self.partition_key,
            "ticker": self.ticker,
            "coin_name": self.coin_name,
            "symbol": self.symbol,
            "current_price": self.current_price,
            "price_change_24h": self.price_change_24h,
            "volume_24h": self.volume_24h,
            "volume_rank": self.volume_rank,
            "price_history": self.price_history,
            "analysis_timestamp": self.analysis_timestamp.isoformat(),
            "data_source": self.data_source,
            "version": self.version,
        }
        
        if self.gemini_insight:
            item["gemini_insight"] = self.gemini_insight.to_dict()
        
        return item
    
    @classmethod
    def from_dynamodb_item(cls, item: dict[str, Any]) -> "CoinAnalysis":
        """Create from DynamoDB item."""
        gemini_insight = None
        if "gemini_insight" in item:
            gemini_insight = GeminiInsight.from_dict(item["gemini_insight"])
        
        return cls(
            partition_key=item["pk"],
            ticker=item["ticker"],
            coin_name=item["coin_name"],
            symbol=item.get("symbol", f"{item['ticker']}USDT"),
            current_price=item["current_price"],
            price_change_24h=item["price_change_24h"],
            volume_24h=item["volume_24h"],
            volume_rank=item["volume_rank"],
            price_history=item.get("price_history", []),
            gemini_insight=gemini_insight,
            analysis_timestamp=datetime.fromisoformat(item["analysis_timestamp"]),
            data_source=item.get("data_source", "bitget"),
            version=item.get("version", "1.0"),
        )
